name: Publish F# Project

on:
  release:
    types: [created]

jobs:

  build-and-publish:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            rid: linux-x64
          - os: macos-latest
            rid: osx-x64
          - os: windows-latest
            rid: win-x64
            
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish single file executable
        run: dotnet publish -c Release -r ${{ matrix.rid }} --self-contained true /p:PublishSingleFile=true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ToolboxLiberator-${{ matrix.rid }}
          path: |
            bin/Release/net8.0/${{ matrix.rid }}/publish/ToolboxLiberator

  upload-release-assets:
  
    needs: build-and-publish
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ToolboxLiberator-linux-x64
          path: linux-x64/
      
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ToolboxLiberator-osx-x64
          path: osx-x64/

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ToolboxLiberator-win-x64
          path: win-x64/

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Authenticate GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      - name: Upload Linux artifact to release
        run: gh release upload ${{ github.event.release.tag_name }} linux-x64/*

      - name: Upload macOS artifact to release
        run: gh release upload ${{ github.event.release.tag_name }} osx-x64/*

      - name: Upload Windows artifact to release
        run: gh release upload ${{ github.event.release.tag_name }} win-x64/*
